"""Umm al-Qura conversion fixtures against published reference dates and a
Node/ICU parity fixture generated by `backend/scripts/verify_umalqura.mjs`.
"""

from __future__ import annotations

import json
from datetime import date
from pathlib import Path

import pytest

from app.features.cultural_events.umalqura import (
    UMALQURA_YEAR_END,
    UMALQURA_YEAR_START,
    UmalquraOutOfRangeError,
    current_hijri_year,
    gregorian_to_hijri,
    hijri_date_key,
    hijri_to_gregorian,
)

# Officially published Umm al-Qura calendar dates (Saudi Arabia). Independent of
# both this module and the frontend's Intl output — a shared bug would still fail.
_PUBLISHED: list[tuple[int, int, int, str]] = [
    (1447, 9, 1, "2026-02-18"),  # 1 Ramadan 1447
    (1447, 10, 1, "2026-03-20"),  # 1 Shawwal / Eid al-Fitr
    (1447, 12, 10, "2026-05-27"),  # 10 Dhul-Hijjah / Eid al-Adha
    (1448, 9, 1, "2027-02-08"),
    (1448, 10, 1, "2027-03-09"),
    (1448, 12, 10, "2027-05-16"),
    (1449, 9, 1, "2028-01-28"),
    (1449, 10, 1, "2028-02-26"),
    (1449, 12, 10, "2028-05-05"),
]


@pytest.mark.parametrize(("hy", "hm", "hd", "expected"), _PUBLISHED)
def test_published_umm_al_qura_dates(hy: int, hm: int, hd: int, expected: str) -> None:
    assert hijri_to_gregorian(hy, hm, hd).isoformat() == expected


def test_hijri_date_key_matches_and_offsets() -> None:
    assert hijri_date_key(1447, 10, 1) == "2026-03-20"
    # Day before 1 Shawwal is the last day of Ramadan.
    assert hijri_date_key(1447, 10, 1, day_offset=-1) == "2026-03-19"


def test_round_trip_across_full_table() -> None:
    for hy in range(UMALQURA_YEAR_START, UMALQURA_YEAR_END + 1):
        for hm in (1, 6, 12):
            g = hijri_to_gregorian(hy, hm, 1)
            assert gregorian_to_hijri(g) == (hy, hm, 1)


def test_out_of_range_raises() -> None:
    with pytest.raises(UmalquraOutOfRangeError):
        hijri_to_gregorian(1299, 1, 1)
    with pytest.raises(UmalquraOutOfRangeError):
        hijri_to_gregorian(1601, 1, 1)


def test_current_hijri_year_for_known_date() -> None:
    # 2026-03-01 is still in Ramadan 1447 (ends 2026-03-19).
    assert current_hijri_year(date(2026, 3, 1)) == 1447


def test_parity_with_node_icu_fixture() -> None:
    fixture = Path(__file__).parents[1] / "fixtures" / "umalqura_node_parity.json"
    if not fixture.exists():
        pytest.skip("parity fixture not generated yet — run scripts/verify_umalqura.mjs")
    data = json.loads(fixture.read_text())
    for entry in data["dates"]:
        hy, hm, hd = entry["hijri"]
        assert hijri_to_gregorian(hy, hm, hd).isoformat() == entry["gregorian"]
